title: "AVAR   )'(  Jätkuloome. Looming. Vaimustus"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0.3125
  lightness: 1
  brandColors:
    - '#fefcff'
    - '#000000'
    - '#003200'
    - '#a9c1ab'
    - '#438931'
  rhythmicContrast: 0.5555556
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Avar
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8835126
layout_spectrum: 0.40606
