name: Avar
favicon: null
layout_spectrum: 0.4729289950337261
typography_spectrum: 0.7059064484201372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5449645044282079
  lightness: 0.685848324559629
  saturation: 0.7872857144102454
  rhythmicContrast: 0.7969912292901427
purpose: []
