name: Avar
favicon: null
layout_spectrum: 0.40606
typography_spectrum: 0.44956
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "AVAR   )'(  Jätkuloome. Looming. Vaimustus"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefcff'
    - '#000000'
    - '#003200'
    - '#a9c1ab'
    - '#438931'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
